### ISSUE TITLE
Not working with Chrome as on Sep 15, 2020

### ISSUE THREAD

**Issue by hkimscil** [cosmocode/dokuwiki-plugin-imgpaste#18]
Chrome version:
Version 87.0.4259.3 (Official Build) dev (64-bit)

in Windows 10

Ctrl-V does not do anything with dokuwiki hogfather latest.

**Comment by philtreF** [comment]
Hello, 

I have the same type of issue with the latest version of Dokuwiki
When I paste a screenshot from greenshot I have this error in Chrome's console : 

`js.php?t=bootstrap3&tseed=742cb89d815ae410ef61e92a3e0eb2f0:1 Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at js.php?t=bootstrap3&tseed=742cb89d815ae410ef61e92a3e0eb2f0:1
    at Array.forEach (<anonymous>)
    at HTMLHtmlElement.<anonymous> (js.php?t=bootstrap3&tseed=742cb89d815ae410ef61e92a3e0eb2f0:1)
    at HTMLHtmlElement.dispatch (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
    at HTMLHtmlElement.v.handle (jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2)
`

And this error in Firefox console: 

`Uncaught TypeError: FileReader.readAsDataURL: Argument 1 is not an object.`

I tried disabling most of my plugins and this does not help.
Let me know if I can help troubleshoot this further.

Thanks,
Fred

**Comment by mh72sp** [comment]
Hello,
I can report the same issue in Firefox 85.0. Is this plugin still under development?
Best regards

**Comment by bby-bishopclark** [comment]
> Ctrl-V does not do anything with dokuwiki hogfather latest.

Even with small images?

A similar project seems to be suffering too, but they just put a try() around it:

https://github.com/layerssss/paste.js/commit/b8b370759507ed07f89b34fa0ac27eac0879ef7e

ours would be equally cheesy:

```diff
--- a/jquery.paste_image_reader.js
+++ b/jquery.paste_image_reader.js
@@ -44,7+44,8 @@ class Paste
                        return;
                    }
                    if (type.match(options.matchType) || clipboardData.items[i].type.match(options.matchType)) {
+                    try
                        file = clipboardData.items[i].getAsFile();
                        reader = new FileReader();
                        reader.onload = function (evt) {
```

Is it worth it?

**Comment by bendavidbp** [comment]
Not working in Chrome Version 93.0.4577.63 (Official Build) (64-bit).  Is this still being maintained?  This ticket has been open since 2020.

**Comment by bby-bishopclark** [comment]
> Not working in Chrome Version 93.0.4577.63 (Official Build) (64-bit).

1.  did chrome's console give the same output?

2. did the fix above alter the behaviour for you?

> Is this still being maintained? This ticket has been open since 2020.

Those two ideas don't often correlate.  I think I'm waiting on a chrome bug I reported a decade ago.  I *know* I'm waiting on a mozilla bug dating back even further.

**Comment by bendavidbp** [comment]
I'm not getting any output on the console.  The fix above did not work for me.

**Comment by bendavidbp** [comment]
It looks like there were two errors in the console that were hidden when the page first loads.  There was no additional console ouput when I attempted the paste.

1.
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
jquery.php:1
Learn more: User-Agent String Reduction

2.
Page layout may be unexpected due to Quirks Mode
One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications.
Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be `<!DOCTYPE html>` to render the page in No Quirks Mode.
1 element
Document in the DOM tree	Mode	URL
document	Limited Quirks Mode	http://10.215.76.105/pricing/dokuwiki/doku.php?id=test_page&do=edit&rev=1631222739
Learn more: Document compatibility mode

**Comment by sokolgeo** [comment]
Does not work on Firefox 93.0 (64-bit) with Hogfather release either.

**Comment by cepm-nate** [comment]
Currently not working for me either. Pasting has no effect: No logged output in the console, no change in the text edit box..etc.

Dokuwiki: Release 2020-07-29 "Hogfather"
Chrome: Version 100.0.4896.88
OS: Windows 10

Anyone have it working with Hogfather?

**Comment by splitbrain** [comment]
works for me
